openapi: "3.0.0"
info:
  title: dropbox
  description: "drop description"
  termsOfService: https://editor.swagger.io/ or https://editor-next.swagger.io/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
servers:
  - url: http://localhost:8085
tags:
  - name: user
    description: Operations about user
    externalDocs:
      url: https://editor-next.swagger.io/
  - name: file
    description: Operations about file
    externalDocs:
      url: https://editor-next.swagger.io/
#components:
#  schemas:
#    UserRegistrationRq: { $ref: "./schemas/user/UserRegistrationRq.yml" }
#    UserFileUploadRq: { $ref: "./schemas/user/UploadFileDtoRq.yml" }
paths:
  /api/v1/users:
    $ref: "./paths/user.yml"
  /api/v1/users/{id}:
    $ref: "./paths/user_id.yml"
  /api/v1/users/{id}/files:
    $ref: "./paths/user_id_file.yml"
  /api/v1/files:
    $ref: "./paths/file.yml"
  /api/v1/files/{id}:
    $ref: "./paths/file_id.yml"
