server:
  port: 8085
  shutdown: graceful

logging:
  level:
    root: INFO
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.zalando.logbook: TRACE
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    properties.hibernate:
      enable_lazy_load_no_trans: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
telegram:
  bot:
    name: komarov_cnt_bot
    token: 6761589731:AAG95kAz3-FVgEnjSw0z_qhkB973E_dZyes
