server:
  ports: 8080
  shutdown: graceful

spring:
  main:
    banner-mode: off
  data:
    mongodb:
      username: rootuser
      password: rootpass
      database: users
      port: 27017
      host: localhost
