server:
  ports: 8080
  shutdown: graceful

spring:
  main:
    banner-mode: off
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: user_db
      port: 27017
      host: localhost
      auto-index-creation: true
